params = {
    "ETH": {
        "optimal_usage": 0.45,
        "base_variable_rate": 0,
        "variable_rate_slope1": 0.04,
        "variable_rate_slope2": 3,
        "base_stable_rate": 0.02,
        "stable_rate_slope1": 0.07,
        "stable_rate_slope2": 3,
        "optimal_stable_to_total_debt_ratio": 0.2,
    },
    "BTC": {
        "optimal_usage": 0.45,
        "base_variable_rate": 0,
        "variable_rate_slope1": 0.04,
        "variable_rate_slope2": 3,
        "base_stable_rate": 0.02,
        "stable_rate_slope1": 0.07,
        "stable_rate_slope2": 3,
        "optimal_stable_to_total_debt_ratio": 0.2,
    },
    "USDC": {
        "optimal_usage": 0.8,
        "base_variable_rate": 0,
        "variable_rate_slope1": 0.04,
        "variable_rate_slope2": 0.75,
        "base_stable_rate": 0.01,
        "stable_rate_slope1": 0.005,
        "stable_rate_slope2": 0.75,
        "optimal_stable_to_total_debt_ratio": 0.2,
    },
    "DAI": {
        "optimal_usage": 0.9,
        "base_variable_rate": 0,
        "variable_rate_slope1": 0.04,
        "variable_rate_slope2": 0.6,
        "base_stable_rate": 0.02,
        "stable_rate_slope1": 0.005,
        "stable_rate_slope2": 0.6,
        "optimal_stable_to_total_debt_ratio": 0.2,
    },
}
